<?php
/**
 * Plugin Name: infiRewards – Loyalty Points & Rewards
 * Description: Loyalty points and rewards for WooCommerce.
 * Version:     0.1.0
 * Author:      Infivro
 * Text Domain: infirewards
 */

defined( 'ABSPATH' ) || exit;

// Composer autoload (vendor/autoload.php should be generated by running composer install)
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
	require_once __DIR__ . '/vendor/autoload.php';
}

// Define plugin constants
if ( ! defined( 'INFIREWARDS_VERSION' ) ) {
	define( 'INFIREWARDS_VERSION', '0.1.0' );
}

if ( ! defined( 'INFIREWARDS_PLUGIN_FILE' ) ) {
	define( 'INFIREWARDS_PLUGIN_FILE', __FILE__ );
}

if ( ! defined( 'INFIREWARDS_PLUGIN_DIR' ) ) {
	define( 'INFIREWARDS_PLUGIN_DIR', __DIR__ );
}

// Boot the plugin (uses InfiRewards\Core\Plugin)
try {
	if ( class_exists( \InfiRewards\Core\Plugin::class ) ) {
		\InfiRewards\Core\Plugin::get_instance()->boot();
	}
} catch ( Throwable $e ) {
	// Fail silently in WP environment; admin notices could be added.
}

// Register activation hook to create database tables.
// This will create the following tables using dbDelta:
// - {prefix}infirewards_wallets (wallet_id, user_id, balance, updated_at)
// - {prefix}infirewards_transactions (transaction_id, user_id, order_id, points, reason, created_at)
// - {prefix}infirewards_rules (rule_id, type, config, points, status)
// dbDelta handles charset, collation, and creating/updating indexes safely. The installer is idempotent.
register_activation_hook(
	__FILE__,
	function () {
		if ( class_exists( \InfiRewards\Database\Installer::class ) ) {
			// Use the Installer singleton to create or update required tables.
			\InfiRewards\Database\Installer::get_instance()->install();
		}
	}
);

// Optional: placeholder for uninstall cleanup (remove options, custom tables, etc.).
// To implement, create a static uninstall handler and register with register_uninstall_hook.

/**
 * Uninstall handler wrapper.
 * WordPress will include this plugin file before calling the uninstall callback, so ensure
 * the Installer class is available (composer autoload may be required).
 * This function delegates to the Installer singleton to perform table drops and cleanup.
 */
function infirewards_uninstall(): void {
	// Attempt to load autoloader if present
	if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
		require_once __DIR__ . '/vendor/autoload.php';
	}

	if ( class_exists( \InfiRewards\Database\Installer::class ) ) {
		\InfiRewards\Database\Installer::get_instance()->uninstall();
	}
}

register_uninstall_hook( __FILE__, 'infirewards_uninstall' );
